CREATE TABLE "customers" (
  "id"         UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  "code"       VARCHAR(20)  NOT NULL UNIQUE,
  "name_ar"    VARCHAR(200) NOT NULL,
  "phone"      VARCHAR(30),
  "active"     BOOLEAN      NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TABLE "customer_transactions" (
  "id"                  UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  "customer_id"         UUID          NOT NULL REFERENCES "customers"("id"),
  "type"                VARCHAR(20)   NOT NULL CHECK ("type" IN ('INVOICE','RECEIPT','RETURN','ADJUSTMENT','OPENING')),
  "direction"           VARCHAR(2)    NOT NULL CHECK ("direction" IN ('DR','CR')),
  "amount"              DECIMAL(14,2) NOT NULL,
  "date"                DATE          NOT NULL,
  "reference"           VARCHAR(100),
  "description"         VARCHAR(300),
  "payment_account_id"  UUID          REFERENCES "payment_accounts"("id"),
  "created_by"          UUID          NOT NULL REFERENCES "users"("id"),
  "created_at"          TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);
CREATE INDEX "customer_tx_customer_idx" ON "customer_transactions"("customer_id");
CREATE INDEX "customer_tx_date_idx"     ON "customer_transactions"("customer_id","date");

INSERT INTO "customers" ("id","code","name_ar","active","created_at") VALUES
(gen_random_uuid(),'CST001','م أحمد زهيري',true,NOW()),
(gen_random_uuid(),'CST002','م حسن سمير',true,NOW()),
(gen_random_uuid(),'CST003','م محمد فرحات',true,NOW()),
(gen_random_uuid(),'CST004','م عمر',true,NOW()),
(gen_random_uuid(),'CST005','م عبده قطر',true,NOW()),
(gen_random_uuid(),'CST006','م أحمد الديب',true,NOW()),
(gen_random_uuid(),'CST007','م أحمد عاطف',true,NOW()),
(gen_random_uuid(),'CST008','م رمضان بنها',true,NOW()),
(gen_random_uuid(),'CST009','م صلاح مكي',true,NOW()),
(gen_random_uuid(),'CST010','م أشرف محمد',true,NOW()),
(gen_random_uuid(),'CST011','م أحمد بخيت',true,NOW()),
(gen_random_uuid(),'CST012','م محمود مبروك',true,NOW()),
(gen_random_uuid(),'CST013','م أيمن العمده',true,NOW()),
(gen_random_uuid(),'CST014','م محمد عبدالرحيم',true,NOW()),
(gen_random_uuid(),'CST015','م محمود ميجا',true,NOW()),
(gen_random_uuid(),'CST016','م محمد جوده',true,NOW()),
(gen_random_uuid(),'CST017','م محمد رجب الجماليه',true,NOW()),
(gen_random_uuid(),'CST018','م محمد عماد',true,NOW()),
(gen_random_uuid(),'CST019','م حسام زكريا',true,NOW()),
(gen_random_uuid(),'CST020','م حافظ السيد',true,NOW()),
(gen_random_uuid(),'CST021','م محمد الفردقه',true,NOW()),
(gen_random_uuid(),'CST022','م أحمد حسن حوامديه',true,NOW()),
(gen_random_uuid(),'CST023','م محمد مزيكا',true,NOW()),
(gen_random_uuid(),'CST024','م محمد رجب شبرا',true,NOW()),
(gen_random_uuid(),'CST025','م حماده السعي',true,NOW()),
(gen_random_uuid(),'CST026','م أحمد لبيب اسماعيليه',true,NOW()),
(gen_random_uuid(),'CST027','م أشرف اسكندريه',true,NOW()),
(gen_random_uuid(),'CST028','م عبدالرحمن الشعراوي',true,NOW()),
(gen_random_uuid(),'CST029','م بسام الفيوم',true,NOW()),
(gen_random_uuid(),'CST030','م عمرو الفيل',true,NOW()),
(gen_random_uuid(),'CST031','م أحمد سيد الفردقه',true,NOW()),
(gen_random_uuid(),'CST032','م اسلام تكنو',true,NOW()),
(gen_random_uuid(),'CST033','م محمد هيكل',true,NOW()),
(gen_random_uuid(),'CST034','م حسام طارق حسين',true,NOW()),
(gen_random_uuid(),'CST035','م بيتر سمير',true,NOW()),
(gen_random_uuid(),'CST036','م محمد زوكا',true,NOW()),
(gen_random_uuid(),'CST037','م ترمين محمد حسين',true,NOW()),
(gen_random_uuid(),'CST038','م علي المهدي',true,NOW()),
(gen_random_uuid(),'CST039','م عماد حمدي',true,NOW()),
(gen_random_uuid(),'CST040','م كريم المصري',true,NOW()),
(gen_random_uuid(),'CST041','م بدر السمبلاوين',true,NOW()),
(gen_random_uuid(),'CST042','م عطيه الحداد',true,NOW()),
(gen_random_uuid(),'CST043','م محمود خاطر',true,NOW()),
(gen_random_uuid(),'CST044','م محمد الطاير',true,NOW()),
(gen_random_uuid(),'CST045','م علي الاحمدي موزع',true,NOW()),
(gen_random_uuid(),'CST046','م محمود العوني م نصر',true,NOW()),
(gen_random_uuid(),'CST047','م أحمد العشري',true,NOW()),
(gen_random_uuid(),'CST048','م أحمد العبد',true,NOW()),
(gen_random_uuid(),'CST049','م ثروت',true,NOW()),
(gen_random_uuid(),'CST050','م محمود سعيد',true,NOW()),
(gen_random_uuid(),'CST051','م أيمن اليماني',true,NOW()),
(gen_random_uuid(),'CST052','م حماده حمدي',true,NOW()),
(gen_random_uuid(),'CST053','م الحسيني فيصل',true,NOW()),
(gen_random_uuid(),'CST054','م اسلام اسامه',true,NOW())
ON CONFLICT ("code") DO NOTHING;
