export interface ApColor {
  code: string;
  nameAr: string;
}

export const AP_COLORS: ApColor[] = [
  { code: "AP 120",  nameAr: "سيلفر ميتالك" },
  { code: "AP 250",  nameAr: "دارك جراي" },
  { code: "AP 115",  nameAr: "رمادي ساده" },
  { code: "AP 385",  nameAr: "جراي فاتح" },
  { code: "AP D1",   nameAr: "ابيض لامع" },
  { code: "AP 788",  nameAr: "ابيض مط" },
  { code: "AP 9005", nameAr: "اسود لامع" },
  { code: "AP 9010", nameAr: "اسود مط" },
  { code: "AP 113",  nameAr: "اوف وايت مط" },
  { code: "AP 442",  nameAr: "بيج غامق" },
  { code: "AP 276",  nameAr: "احمر لامع" },
  { code: "AP 1010", nameAr: "خشبي" },
  { code: "AP 302",  nameAr: "مرايا دهبي" },
  { code: "AP 1023", nameAr: "اصفر" },
  { code: "AP 116",  nameAr: "كحلي" },
  { code: "AP 117",  nameAr: "ازرق" },
  { code: "AP 111",  nameAr: "اخضر" },
  { code: "AP 375",  nameAr: "رمادي غامق" },
  { code: "AP 119",  nameAr: "سيلفر مط" },
  { code: "AP D4",   nameAr: "لبني فاتح" },
  { code: "AP 134",  nameAr: "لبني غامق" },
  { code: "AP 2004", nameAr: "اوراجنج" },
  { code: "AP 301",  nameAr: "فضي مرايا" },
  { code: "AP 114",  nameAr: "شامبين سيلفر" },
  { code: "AP 183",  nameAr: "شامبين جولد" },
  { code: "AP D2",   nameAr: "لايت جراي" },
  { code: "AP 944",  nameAr: "ازرق ميتالك" },
  { code: "AP 113G", nameAr: "اوف وايت لامع" },
  { code: "AP 180",  nameAr: "ابيض ميتالك" },
  { code: "AP 056",  nameAr: "بني" },
  { code: "AP 055",  nameAr: "بني شيكولاته" },
  { code: "AP 3005", nameAr: "نبيتي" },
  { code: "AP 130",  nameAr: "دهبي ميتالك" },
  { code: "AP 106",  nameAr: "نحاسي" },
  { code: "AP 765",  nameAr: "اخضر امان" },
  { code: "AP 672",  nameAr: "اخضر نفايتي" },
  { code: "AP 110",  nameAr: "اخضر ابيو" },
  { code: "AP 023",  nameAr: "اخضر زيتي" },
  { code: "AP 160",  nameAr: "موف" },
  { code: "AP 170",  nameAr: "بينك" },
  { code: "AP 401",  nameAr: "فضي براشد" },
  { code: "AP 402",  nameAr: "دهبي براشد" },
  { code: "AP 777",  nameAr: "خشبي بارز" },
  { code: "AP 1008", nameAr: "خشبي 1008" },
  { code: "AP 501",  nameAr: "كونكريت غامق" },
  { code: "AP 503",  nameAr: "كونكريت فاتح" },
  { code: "AP 216",  nameAr: "رخامي فاتح" },
  { code: "AP 215",  nameAr: "رخامي غامق" },
];

export const apColorMap = new Map(AP_COLORS.map((c) => [c.code, c]));
